apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-0
spec:
  serviceName: kafka-0
  replicas: 1
  selector:
    matchLabels:
      app: kafka-0
  template:
    metadata:
      labels:
        app: kafka-0
    spec:
      containers:
      - name: kafka-0
        #image: docker.io/arjun/kafka:v2
        image: arjunvkrishna/kafka:1.0.1
        ports:
        - containerPort: 9092
        env:
        # KRaft settings
        - name: KAFKA_CFG_NODE_ID
          value: "0"
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "controller,broker"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: "0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093"
        - name: KAFKA_KRAFT_CLUSTER_ID
          value: "abcdefghijklmnopqrstuv"
        # Listeners
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        # Clustering
        - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
          value: "2"
        - name: KAFKA_CFG_NUM_PARTITIONS
          value: "32"
        - name: KAFKA_CFG_LOG_RETENTION_HOURS
          value: "600000"
        volumeMounts:
        - name: kafka-storage-0
          mountPath: /bitnami/kafka/
      volumes:
      - name: kafka-storage-0
        persistentVolumeClaim:
          claimName: kafka-0-pvc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-1
spec:
  serviceName: kafka-1
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
      - name: kafka-1
        #image: docker.io/arjun/kafka:v2
        image: arjunvkrishna/kafka:1.0.1
        ports:
        - containerPort: 9092
        env:
        # KRaft settings
        - name: KAFKA_CFG_NODE_ID
          value: "1"
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "controller,broker"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: "0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093"
        - name: KAFKA_KRAFT_CLUSTER_ID
          value: "abcdefghijklmnopqrstuv"
        # Listeners
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        # Clustering
        - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
          value: "2"
        - name: KAFKA_CFG_NUM_PARTITIONS
          value: "32"
        - name: KAFKA_CFG_LOG_RETENTION_HOURS
          value: "600000"
        volumeMounts:
        - name: kafka-storage-1
          mountPath: /bitnami/kafka/
      volumes:
      - name: kafka-storage-1
        persistentVolumeClaim:
          claimName: kafka-1-pvc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-2
spec:
  serviceName: kafka-2
  replicas: 1
  selector:
    matchLabels:
      app: kafka-2
  template:
    metadata:
      labels:
        app: kafka-2
    spec:
      containers:
      - name: kafka-2
        #image: docker.io/arjun/kafka:v2
        image: arjunvkrishna/kafka:1.0.1
        ports:
        - containerPort: 9092
        env:
        # KRaft settings
        - name: KAFKA_CFG_NODE_ID
          value: "2"
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "controller,broker"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: "0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093"
        - name: KAFKA_KRAFT_CLUSTER_ID
          value: "abcdefghijklmnopqrstuv"
        # Listeners
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        # Clustering
        - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
          value: "2"
        - name: KAFKA_CFG_NUM_PARTITIONS
          value: "32"
        - name: KAFKA_CFG_LOG_RETENTION_HOURS
          value: "600000"
        volumeMounts:
        - name: kafka-storage-2
          mountPath: /bitnami/kafka/
      volumes:
      - name: kafka-storage-2
        persistentVolumeClaim:
          claimName: kafka-2-pvc